### ISSUE TITLE
navbar auto-hide.css not working since 65.0b1

### ISSUE THREAD

**Issue by MikulasZelinka** [Timvde/UserChrome-Tweaks#124]
Hello,

not sure if this is perhaps a bug in the Developer Edition but since yesterday (and build 65.0b1, Firefox Developer Edition), the autohide of the navigation bar is not working properly.

![image](https://pasteboard.co/HQvdRVv.png)

**Comment by different55** [comment]
Looks a lot like the problems I had when --tab-min-height wasn't set quite right. Guess they changed some of the dimensions in the update. If you want to go looking for a solution yourself, just tweak `--tab-min-height` for your UI density. If you can't, I'll probably deal with it when I update.

**Comment by different55** [comment]
Not seeing any problems like this since I've updated to FF65.

**Comment by Timvde** [comment]
So I can close this?

**Comment by lokmeinmatz** [comment]
yeah i fixed it, changed the --tabbar-height calculation to ` --tabbar-height: calc(var(--tab-min-height) + 7px);`, feels a bit hacky but works for me, the tab-min-height was correct for me

**Comment by Timvde** [comment]
Wait, so is a fix to the code needed or not?

**Comment by ana-ka** [comment]
> Not seeing any problems like this since I've updated to FF65.

I am having the issue with FF65 and FF66 beta on windows. When I maximize Firefox, it looks like the screenshot in the first post. When not maximized, it looks quite okay, but not perfect. There is noticable "bobbing" when the navbar transitions in and out. Also the actual webpage overlays the tabbar for a brief moment before it slides down and pops up again. I will try the "fix" that was posted above and can provide screenshots if needed. I'll be back with an update.

**Comment by MikulasZelinka** [comment]
@Timvde A fix is needed, the issue persist, as described by @ana-ka.

**Comment by different55** [comment]
Hm. Still not seeing any issues on Linux, so we need to be careful that whatever Windows fix is needed doesn't break other platforms.

**Comment by ana-ka** [comment]
Alright, today I tried the fix suggested by @lokmeinmatz again on FF66b5 and FF65 and I was just about to call the issue fixed. But here is what I noticed:

On my main screen (2560x1440, OS scaling on Windows) both, FF66 und 65 look as intended or close to it with 

`--tabbar-height: calc(var(--tab-min-height) + 7px);` instead of
`--tabbar-height: calc(var(--tab-min-height) + var(--space-above-tabbar));`

with both compact and normal density and the extra drag space turned off. No matter if the window is maximized or normal. On my secondary screen (1280x1024), it still looks like in the screenshots above (which means slightly broken, even with the fix), that were all taken on that screen. With the drag space turned on in FF, everything is completely broken, similar or identical to the vanilla auto-hide.css.

What still remains on both screens and regardless of other settings is the weird transition, but I cannot say for sure if that was there with prevsious versions already. I had the transition time dialed down to 0.10s and its not as annoying as before. Still the symptoms stay the same. The whole page is bobbing down and up again during the transition and the tabbar is overlayed with the page during transition time, which looks a bit ugly still. I don't know if there is a way to fix that or if it was like this before already. In the end the navbar occludes the webpage, which is to be expected I guess and doesn't bother me.

For now I'll live with the "fix" which is certainly an improvement over vanilla on my setup. Let me know if there is anything I can try to help and improve the situation across all platforms. Good hunting!

**Comment by Jorge9810** [comment]
The fix provided by @lokmeinmatz also worked on my end for the most part. The only issue remaining is when I set Firefox to window mode instead of maximized window.
![firefox-2019-02-10_23-48-37](https://user-images.githubusercontent.com/43153921/52544304-c0841b80-2d8e-11e9-8d91-4e5036788d87.png)

**Comment by paulscholes0258** [comment]
> 
> 
> The fix provided by @lokmeinmatz also worked on my end for the most part. The only issue remaining is when I set Firefox to window mode instead of maximized window.
> ![firefox-2019-02-10_23-48-37](https://user-images.githubusercontent.com/43153921/52544304-c0841b80-2d8e-11e9-8d91-4e5036788d87.png)

Hi Jorge9810
can you share me o code or file userChrome.css that you''re using.
thanks Jorge9810

**Comment by paulscholes0258** [comment]
> 
> 
> > Not seeing any problems like this since I've updated to FF65.
> 
> I am having the issue with FF65 and FF66 beta on windows. When I maximize Firefox, it looks like the screenshot in the first post. When not maximized, it looks quite okay, but not perfect. There is noticable "bobbing" when the navbar transitions in and out. Also the actual webpage overlays the tabbar for a brief moment before it slides down and pops up again. I will try the "fix" that was posted above and can provide screenshots if needed. I'll be back with an update.
> 
> Update: With the "fix" above its more visually pleasing but still broken. Now I got a permanent black bar (maybe black because of dark theme?) in the place where the navbar is supposed to be. Also when the navbar is visible, its only less broken than before but not perfect. There is a thin space between tabbar and navbar where the actual page shines through, with the active tab beeing a little bit thinker than the other ones. I will compile a series of screenshots and be back with that.
> 
> Update2: The "fix" somewhat worked in the end - no idea why it didn't when I tried first. Still not perfect.
> 
> vanilla_maxed
> ![vanilla_maxed](https://user-images.githubusercontent.com/30725490/52207788-c48bd700-287e-11e9-96d1-373d4e4054bd.jpg)
> 
> vanilla_normal
> ![vanilla_normal](https://user-images.githubusercontent.com/30725490/52207807-d3728980-287e-11e9-9580-79eefaf6914a.jpg)
> 
> fix_maxed
> ![fix_max](https://user-images.githubusercontent.com/30725490/52207814-da999780-287e-11e9-92b0-65adae314c08.jpg)
> 
> fix_normal
> ![fix_normal](https://user-images.githubusercontent.com/30725490/52207825-e1c0a580-287e-11e9-884d-d606cae44dd7.jpg)
> 
> weird transition
> ![transition](https://user-images.githubusercontent.com/30725490/52207831-e7b68680-287e-11e9-8719-c53fd9b7eb09.jpg)
> 
> The transition is hard to capture. The white stripe you see appears to be the webpage in the background and extends over the whole tabbar for a brief moment before sliding down. Looks kinda ugly.
> 
> If you need any more info, let me know.

Hi ana-ka
can you share me the code or file userChrome.css that you''re using.
thanks ana-ka

**Comment by different55** [comment]
I might be remembering wrong but I think --space-above-tabbar represents the amount of dragspace when that option's enabled.

**Comment by gaveitatry** [comment]
I am using my own userchrome.css to autohide the Navigation Bar, and it is much better.


There is one main reason that I don't like Timvde's code.  Whenever you mouse hover to make the navigation bar appear, it displays the page's content in the tabs bar for a split second.

Another reason that I don't like Timvde's code is that it is so damn long.  It is easily 50 lines of code.

So I did some searching online and I found this following webpage:
https://www.reddit.com/r/FirefoxCSS/comments/7dazk8/looking_for_autohide_navigation_bar_css_snippet/

I changed the height from 2.7em to 40px for my computer and browser and I removed a few !important snippets of code because they don't seem necessary.  I also added a #nav-bar:focus-within rule, which is essential.

The resulting code was this:

```
#nav-bar {
min-height: 0 !important;
max-height: 0;
margin-bottom: -40px;
overflow-y:hidden;
opacity: 0;
transition: opacity 0.2s, max-height 0.2s;}

:hover > #nav-bar, #nav-bar:focus-within { 
max-height: 40px;
opacity: 1;
transition: opacity 0.2s;}
```

It does everything that Timvde's code does, but it uses far less code and you don't see the page's content in the title bar every time that you mouse hover.

I also added another tweak which is optional:

```
#TabsToolbar {
margin-left:-40px;
margin-top:-2px;}
```

The margin-top:-2px moves the tabs up closer to the top of the browser.  That is just my personal preference.  And the margin-left:-40px isn't necessary but that was my way to remove the pre-tabs drag space gap to the left of the tabs.  There was different code to remove the pre-tabs gap, but it wasn't working in my Firefox 65.0 browser for some reason.  I don't know why.  So I just ended up using a margin-left trick.

I don't know if my userchrome.css will work on all browsers on all computers in all circumstances.  I have only been using it for a few minutes and haven't done any extensive testing.  But my gut tells me it may work for most people, so you should give it a try.

I know some people, including myself, would maybe like a way for the navigation bar to not appear over the page contents, but rather appear and also push the page contents so that it is directly below the navigation bar.  There is a Firefox legacy extension that did that.  I might look into this later and see if I can do it too.  It's not that important to me, but maybe when I get bored.

**Comment by raamdev** [comment]
I'm running Firefox Quantum v65.0.1 and was running into the issue with `auto-hide.css` showing a bit of the background page when the address bar re-appeared on hover.

![firefox-issue124-broken](https://user-images.githubusercontent.com/53005/53886385-e8614a80-3fed-11e9-9d19-25d11304ddfe.gif)

I played with the CSS a bit and found that if I commented out the two `transition:` lines, that fixed the problem for me. 

Here's what I started with: 
https://github.com/Timvde/UserChrome-Tweaks/blob/bf0e9c1c53642fa80cd418d23bfdae94e5a8e915/toolbars/auto-hide.css

Here's the two spots where I commented out the `transition:` lines:

```
:root:not([customizing]) #navigator-toolbox {
  max-height: calc(var(--tabbar-height) + var(--trigger-area-height));
  min-height: var(--tabbar-height);
  margin-bottom: calc(-1 * var(--trigger-area-height));
  /*transition: opacity 0.15s ease-in, max-height 0.15s linear;*/
}
```

```
:root:not([customizing]) :hover > #PersonalToolbar,
:root:not([customizing]) #navigator-toolbox:focus-within #PersonalToolbar {
  max-height: 4em !important;
  opacity: 1;
  /*transition: opacity 0.15s ease-in !important;*/
}
```

![firefox-issue124](https://user-images.githubusercontent.com/53005/53886395-ee572b80-3fed-11e9-9928-54c20d6f4285.gif)

**Comment by gaveitatry** [comment]
@raamdev - That sounds great!  I'll give it a try later.  Thank you.

**Comment by Jorge9810** [comment]
So, does anyone know how to fix that issue I brought up earlier?
Even though the fix that @lokmeinmatz came up with works on Fullscreen, if I set Firefox to Window Mode, a black bar appears under my tabs.
